package View;

import javafx.fxml.FXML;

import javafx.scene.control.TextField;
import javafx.stage.Stage;
import javafx.event.ActionEvent;

public class MainSceneController {
	@FXML
	private TextField tfTitel;

	// Event Listener on Button.onAction
	@FXML
	public void btnOkClicked(ActionEvent event) {
		// TODO Autogenerated
		Stage mainStage = (Stage) tfTitel.getScene().getWindow();
		String titel = tfTitel.getText();
		mainStage.setTitle(titel);
	}
}
